server:
  http:
    addr: 0.0.0.0:8105
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9105
    timeout: 1s

data:
  database:
    driver: mysql
    source: root:@tcp(127.0.0.1:3306)/marketing_service?charset=utf8mb4&parseTime=True&loc=Local
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 1h
  redis:
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    dial_timeout: 1s
    read_timeout: 0.2s
    write_timeout: 0.2s
    pool_size: 100
    min_idle_conns: 10
  rocketmq:
    name_servers:
      - "127.0.0.1:9876"
    group_name: "marketing-producer-group"
    retry_times: 2
    send_timeout: 3s
    enabled: false  # 设置为 true 启用 RocketMQ

client:
  tenant_service:
    target: 127.0.0.1:9000
    timeout: 1s
